{% set name = "nginx" %}
{% set version = "1.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://nginx.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: c6b5c6b086c0df9d3ca3ff5e084c1d0ef909e6038279c71c1c3e985f576ff76a
  patches:
    - pcre-config.patch  # find pcre in PREFIX instead of /usr

build:
  number: 0
  no_link:
    - etc/*
    - var/log/nginx/*
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not osx]
    - make
  host:
    - libgd {{ libgd }}
    - libxslt 1.1.*
    - libxml2 {{ libxml2 }}
    - openssl 3.0.8
    - pcre2 {{ pcre2 }}
    - zlib {{ zlib }}
  run:
    - libgd {{ libgd }}
    - libxml2
    - libxslt 1.1.*
    - openssl 3.*
    - pcre2

test:
  requires:
    - curl

about:
  home: https://nginx.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
  description: |
    Nginx can act as a reverse proxy server for TCP, UDP, HTTP, HTTPS, SMTP,
    POP3, IMAP, and gRPC protocols, as well as a load balancer and an HTTP cache.
    Nginx uses an asynchronous event-driven approach to handling requests.
  doc_url: https://nginx.org/en/docs
  dev_url: https://hg.nginx.org/nginx

extra:
  recipe-maintainers:
    - sodre
