{% set name = "nginx" %}
{% set version = "1.21.6" %}
{% set sha256 = "66dc7081488811e9f925719e34d1b4504c2801c81dee2920e5452a86b11405ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://nginx.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - pcre-config.patch  # find pcre in PREFIX instead of /usr

build:
  number: 0
  no_link:
    - etc/*
    - var/log/nginx/*
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - patch       # [not win]
    - m2-patch    # [win]
   host:
    - libgd
    - libxslt
    - libxml2
    - openssl
    - pcre
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [unix]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.nginx.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Nginx is an HTTP and reverse proxy server
  description: |
    Nginx can act as a reverse proxy server for TCP, UDP, HTTP, HTTPS, SMTP,
    POP3, IMAP, and gRPC protocols, as well as a load balancer and an HTTP cache.
    Nginx uses an asynchronous event-driven approach to handling requests.
  doc_url: http://nginx.org/en/docs
  dev_url: http://hg.nginx.org/nginx

extra:
  recipe-maintainers:
    - sodre
