travis:
  secure:
    BINSTAR_TOKEN: m3hKXd0eWWmwTWqVjaUJ40lOGk330pQx46i7WJ/PsBeWBFDC14xktgvXHViBJWpHJ/yLykRG6gkoBbjBidyIiJnyEBauCxCv/o+1iy4oKpLZBV1KfGUq6ARaRmS03M7wpjWiwbPemguAgNtxgHx8CSK/LEuRS+p0aYZ6MhJtNLqr+o22YHLZpqzLSrO/bYplBScvHRA9bD1lYQb574hzF6YKGF15GGUiuaSS8tOg+RDCIxr0WCrhe9yRwSGCDVHfyjS/d22h1pyx2XzObg+LTNm8v5lEE4dxF2I/05iF3GDuhOSqi8oqyY+AWdxLLhjuof8jHgpBqWSEezvNC52Jss1YyNyd/QT12+FMpYaL3WwzYynJ6vS5ndkeT/dc9p9EzQLGvJsvXczKvgMyNa36QHo/61pCn7TCpT4DXVQaBHzgErpcc8rWf3LJHzJOJlsaIQIvcxKhrdvYn3rvC/m+TEDlqz2ANeYd/NXj7Fd4tkoNE6ipRtH02YEvb/F+jqBGA0TMPilgHfVnDgw9HNeA6tAhvy2+jobUK8ls/a474HABLRsCDFDSreDr1/jjGeqx51acaN0uzrQVfxr+Z+Xz0jAZbzLoDewJAzP8LMpSV7Kz0m29IRpqgMVi+U/8dG/r6539XTZ7Yx7MLM/hJfVIO+ZWhBWmxZDjBKy2CXm0VcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
