travis:
  secure:
    BINSTAR_TOKEN: Q5HEKaDnrGR6ov5SHsAt/T/+tyE1HUYf89pHRpqITMtfLDdWGl+C1nM3560JY4Ka3eD1e4lUN9pMlDULjg8fkn3rPuYxhvp6gr9wMG2mwKePbnCbK7tbuSg+cdKyU8LcItccGiWDXzafy9LK4lbESU/bJIgfI6gdO+eGYWztuEVtonlstT0lQTMBQ3eEUOMnIE+Av7kvVVpBzZgsJS2Xz50+zaM2FfgszmjHpETcwp7jqiLd2+JGEL5VFxW9ZQG5Dkn7alAr80aKJWsPqDr8tBuXWbOsXD0bvU+ooHgtc/+Y2yf3OzUpoCuT9T18GsChYMakyH1No0UpRsEMTQwtY+pKaMFZcjmpYQYgt8rGqOpbJnv5sTesQ5m5+eKhtOzoSTTw/nG4QpPWZENsUgQ0lu7F2XXAPrW+0a2+UGwIuLtE6w9ZYUEa3ooq3XNJP0Cl3XjY/ubwpnJ87w83ZhQn1anEQxksAIg23G59NUPkyjuwyGeh9h0Dxlxj3bU8JHlilKDseTw0j6jnTLFH1SGFX6P1i5aLei/75KTo698F4na8zrhwv/9OacPr9s5dXNUUVVBmwydi6W4VIMdvK5qiWWXZhIzgbq4vMSvrNBUhKzusAhBJbcNKZNvKwcJyNCBHq8T9jqT5iDnU6i4k2dINW1XIDGoV4LX2R9/O2sdPzTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
